name: Build & Deploy

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: '${{ secrets.WEB_HOOK }}'
          method: 'POST'
